x-environment: &environment
  # Postgres DB for Django UI

  # PostgreSQL settings
  DB_NAME: ywangvaster
  DB_USERNAME: ywangvaster
  DB_PASSWORD: vast1234star
  DB_HOST: db
  DB_PORT: 5432

  # Do not remove, otherwise postgres container won't initialise properly
  # Just has to be something that's non-zero
  POSTGRES_PASSWORD: password

  # DJango settings
  DEBUG: False
  DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 0.0.0.0 # Add your production URL here
  DJANGO_SUPERUSER_USERNAME:
  DJANGO_SUPERUSER_PASSWORD:
  DJANGO_SUPERUSER_EMAIL:
  DJANGO_SECRET_KEY:
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONUNBUFFERED: 1

networks:
  ywang_vaster-network:
    name: ywang_vaster-network
    driver: bridge

volumes:
  django_media:
  postgres_data:

services:
  db:
    hostname: db
    container_name: db
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    user: postgres
    environment: *environment
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 3

  web:
    hostname: web
    container_name: web
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    environment: *environment
    volumes:
      - ./ywangvaster_webapp:/ywangvaster_webapp
      - django_media:/ywangvaster_media
      - ./logs:/home/app/logs/
    expose:
      - 80
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:80/"
      start_period: 60s
      interval: 60s
      timeout: 20s
      retries: 20
    depends_on:
      db:
        condition: service_healthy

  nginx:
    hostname: nginx
    container_name: nginx
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - ./ywangvaster_webapp:/ywangvaster_webapp
    ports:
      - 80:80
    depends_on:
      web:
        condition: service_healthy

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
