networks:
  ywang_vaster-network:
    name: ywang_vaster-network
    driver: bridge

volumes:
  django_media:
  postgres_data:

services:
  db:
    hostname: db
    container_name: db
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    user: postgres
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 3

  web:
    hostname: web
    container_name: web
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    volumes:
      - ./ywangvaster_webapp:/ywangvaster_webapp
      - django_media:/ywangvaster_media
      - ./logs:/home/app/logs/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
